### ISSUE TITLE
订阅地址可更新，但是更新获得的节点都不可使用

### ISSUE THREAD

**Issue by zhangruikiven** [ivwv/chromego_convert#1]
获得更新后的节点，使用URL test测试，所有节点都显示“超时”。点击连接任意节点，也不可使用。
使用PC端和安卓端的NekoBox都不可以。
但是使用Clash verge获得的节点大部分可以使用。

**Comment by ivwv** [comment]
使用此项目的节点请选择clash meta、Mihomo内核的软件，Android可使用 https://github.com/MetaCubeX/ClashMetaForAndroid ;Windows可使用 https://github.com/clash-verge-rev/clash-verge-rev
